export default {
    "login": "timbl",
    "id": 1254848,
    "node_id": "MDQ6VXNlcjEyNTQ4NDg=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/1254848?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/timbl",
    "html_url": "https://github.com/timbl",
    "followers_url": "https://api.github.com/users/timbl/followers",
    "following_url": "https://api.github.com/users/timbl/following{/other_user}",
    "gists_url": "https://api.github.com/users/timbl/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/timbl/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/timbl/subscriptions",
    "organizations_url": "https://api.github.com/users/timbl/orgs",
    "repos_url": "https://api.github.com/users/timbl/repos",
    "events_url": "https://api.github.com/users/timbl/events{/privacy}",
    "received_events_url": "https://api.github.com/users/timbl/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Tim Berners-Lee",
    "company": "MIT",
    "blog": "http://www.w3.org/People/Berners-Lee",
    "location": "Boston MA USA",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 14,
    "public_gists": 3,
    "followers": 3285,
    "following": 61,
    "created_at": "2011-12-11T01:28:03Z",
    "updated_at": "2019-07-30T22:26:32Z"
  }
  